[build]
  publish = "dist"
  command = "npm run build"

# Serve static JSON files directly
[[redirects]]
  from = "/db/*"
  to = "/db/:splat"
  status = 200
  force = false

# Serve other static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

# SPA fallback for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
